version: "2"
services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    depends_on:
      - web
      - db
    ports:
      - "80:8069"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web:
    image: odoo-xlrd:13.0
    build:
      context: .
      dockerfile: odoo/dockerfile
    restart: always
    container_name: odoo13
    depends_on:
      - db
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./odoo.conf:/etc/odoo/odoo.conf
      - /mnt/loyalty-modules:/mnt/loyalty-modules
    environment:
      - NO_PROXY=127.0.0.1, localhost
  db:
    image: postgres:10
    restart: always
    environment:
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - POSTGRES_DB=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata
volumes:
  odoo-web-data:
  odoo-db-data: